export const characters = [
  "Le père de Martin",
  "Une bretonne",
  "Une dentiste ",
  "Un manager",
  "Une pianiste",
  "Un saucisson ",
  "Un pitit chat tout doux",
  "Un marin",
  "Une michto ",
  "Un végétarien ",
  "Un chef cuisinier",
  "Rose",
  "Un plombier",
  "Une souris",
  "Martin",
  "Une aquarelliste",
  "Hello Kitty",
  "Un fleuriste",
  "Un bricoleur du dimanche",
  "Une joueuse de pétanque",
  "Une surveillante de musée",
  "Un plongeur"
];

export const actions = [
  "code",
  "mange de la charcuterie",
  "fait du velib bleu",
  "se fait opérer de la myopie ",
  "fait un jeu de mot",
  "est ronchon en randonnée",
  "fait une tête mignonne",
  "film un vlog",
  "joue à Minecraft ",
  "se fait masser",
  "rentre tard le soir",
  "rate son train",
  "fait un réhaussement de cils",
  "fait du crossfit",
  "traine au lit",
  "va au marché",
  "va au cinéma ",
  "regarde Topchef",
  "tombe en faisant du block",
  "chante faux",
  "lit un roman",
  "ronfle"
];